#include "machine_empty.h"

#define INITIAL_STATE ST_MP_DISABLED

BEGIN_STATES
	STATE(ST_MP_DISABLED)

	STATE(ST_MP_SWITCH_MODE_HOMING)
	STATE(ST_MP_HH_UNKNOWN)
	STATE(ST_MP_HH_HOMING)

	STATE(ST_MP_SWITCH_MODE_PP)
	STATE(ST_MP_PP_IDLE)
	STATE(ST_MP_PP_SP_NACK)
	STATE(ST_MP_PP_SP_ACK)

	// Only for dirty sinusoid
	STATE(ST_MP_SWITCH_MODE_IP)
	STATE(ST_MP_IP_SINUSOID)
	STATE(ST_MP_IP_SINUSOID_STOP)
END_STATES

BEGIN_EVENTS
	EVENT(EV_MP_DS_OPERATIONAL)		// From DS machine (mch_ds.cc)
	EVENT(EV_MP_DS_INOPERATIONAL)	// From DS machine (mch_ds.cc)

	EVENT(EV_MP_MODE_HOMING)
	EVENT(EV_MP_MODE_PP)
	EVENT(EV_MP_MODE_IP)

	EVENT(EV_MP_HOMED)
	EVENT(EV_MP_NOTHOMED)

	EVENT(EV_MP_SETPOINT_SET)
	EVENT(EV_MP_SETPOINT_ACK)
	EVENT(EV_MP_SETPOINT_NACK)
	EVENT(EV_MP_TARGET_REACHED)

	// Only for dirty sinusoid
	EVENT(EV_MP_SINUSOID_START)
	EVENT(EV_MP_SINUSOID_STOP)
END_EVENTS

BEGIN_FIELDS
	FIELD(intf_t *, interface)
	FIELD(mch_sdo_t *, mch_sdo)
END_FIELDS

BEGIN_CALLBACKS
END_CALLBACKS

GENERATE_DEFAULT_FUNCTIONS
