#undef BEGIN_STATES
#undef STATE
#undef END_STATES

#undef BEGIN_EVENTS
#undef EVENT
#undef END_EVENTS

#undef BEGIN_CALLBACKS
#undef CALLBACK
#undef END_CALLBACKS

#undef BEGIN_FIELDS
#undef FIELD
#undef END_FIELDS

#undef GENERATE_DEFAULT_FUNCTIONS